exports.QUESTIONS = [
	{q: 'Chi è il cantante rock preferito dalla Giulia?', 
	 o: ['Bruce Springsteen', 'Chris Martin', 'Bruce Dickinson', 'Eddie Wedder'],
	 a: 0},
	{q: 'Giulio vorrebbe chiamare suo figlio col nome di un calciatore. Chi?',
	 o: ['Marco Van Basten', 'Michelle Platini', 'Ruud Gullit', 'Roberto Baggio'],
	 a: 3},
	{q: 'Giulia pratica uno sport. Quale?',
	 o: ['Pilates', 'Tai-chi', 'Yoga', 'Lancio del giavellotto'],
	 a: 2},
	{q: 'Completa questa barzelletta "Un gay chiama un taxi, <Scusi, mi apre...?>"',
	 o: ['dietro', 'la porta', 'la strada', 'la busta'],
	 a: 0},
	{q: 'Giulia è una dottoressa. Qual è la sua specializzazione?',
	 o: ['criminologia', 'endocrinologia', 'entomologia', 'equinocrinologia'],
	 a: 1},
	{q: 'Giulio è alto 1.86. In quale quartile della distribuzione delle altezze degli italiani (al 2015) si trova?',
	 o: ['primo', 'secondo', 'terzo', 'quarto'],
	 a: 3},
	{q: 'Giulia è alta 1.80. In quale quartile della distribuzione delle altezze delle italiane (al 2015) si trova?',
	 o: ['primo', 'secondo', 'terzo', 'quarto'],
	 a: 3},
	{q: 'Giulio ha fatto il giochino del dito rotto anche durante la celebrazione?',
	 o: ['Sì, e la Giulia ha riso', 'Sì, e la Giulia l\'ha picchiato', 'No, ma la fatto la Giulia', 'No'],
	 a: 1},
	{q: 'Giulia ha passato circa 10 mesi in uno stato europeo per studio. Quale?',
	 o: ['Olanda', 'Giulianda', 'Belgio', 'Lussemburgo'],
	 a: 0},
	{q: 'Giulio gioca volentieri anche a calcio. Qual è il suo ruolo?',
	 o: ['Attaccante', 'Portiere', 'Centrocampista', 'Difensore'],
	 a: 1} 
]